# Generated by Django 4.2.28 on 2026-02-04 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_test_cases_written', models.PositiveIntegerField(default=0)),
                ('total_test_cases_reviewed', models.PositiveIntegerField(default=0)),
                ('total_test_cases_executed', models.PositiveIntegerField(default=0)),
                ('test_cases_passed', models.PositiveIntegerField(default=0)),
                ('test_cases_failed', models.PositiveIntegerField(default=0)),
                ('test_cases_blocked', models.PositiveIntegerField(default=0)),
                ('test_cases_in_progress', models.PositiveIntegerField(default=0)),
                ('test_cases_future_execution', models.PositiveIntegerField(default=0)),
                ('test_cases_invalid', models.PositiveIntegerField(default=0)),
                ('retested_qa_review_tickets', models.PositiveIntegerField(default=0)),
                ('total_defects_found', models.PositiveIntegerField(default=0)),
                ('defects_raised', models.PositiveIntegerField(default=0)),
                ('ticket_number_with_priority', models.CharField(blank=True, max_length=500)),
                ('total_observations', models.PositiveIntegerField(default=0)),
                ('observations_found', models.PositiveIntegerField(default=0)),
                ('comments_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_reports', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_qareport',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='reports_qar_user_id_a40d6f_idx'), models.Index(fields=['project', 'date'], name='reports_qar_project_5233d1_idx'), models.Index(fields=['date'], name='reports_qar_date_c7c2f3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='qareport',
            constraint=models.UniqueConstraint(fields=('user', 'project', 'date'), name='unique_user_project_date'),
        ),
    ]
