# Generated by Django 4.2.28 on 2026-02-05 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_add_default_project'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('test_cases_written', models.PositiveIntegerField(default=0)),
                ('test_cases_reviewed', models.PositiveIntegerField(default=0)),
                ('test_cases_executed', models.PositiveIntegerField(default=0)),
                ('test_cases_passed', models.PositiveIntegerField(default=0)),
                ('test_cases_failed', models.PositiveIntegerField(default=0)),
                ('test_cases_blocked', models.PositiveIntegerField(default=0)),
                ('test_cases_in_progress', models.PositiveIntegerField(default=0)),
                ('test_cases_future_execution', models.PositiveIntegerField(default=0)),
                ('test_cases_invalid', models.PositiveIntegerField(default=0)),
                ('retested_qa_review_tickets', models.PositiveIntegerField(default=0)),
                ('defects_raised', models.PositiveIntegerField(default=0)),
                ('ticket_number_with_priority', models.CharField(blank=True, max_length=500)),
                ('observations_found', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_worklogs', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='features.feature')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worklogs_worklog',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='worklogs_wo_user_id_857bea_idx'), models.Index(fields=['feature', 'date'], name='worklogs_wo_feature_8a1c63_idx'), models.Index(fields=['date'], name='worklogs_wo_date_3c35d8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='worklog',
            constraint=models.UniqueConstraint(fields=('user', 'feature', 'date'), name='unique_user_feature_date'),
        ),
    ]
